/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE_ADDR			0x40023800UL

#define RCC_CR_REG_OFFSET		0x00
#define RCC_CR_REG_ADDR			(RCC_BASE_ADDR+RCC_CR_REG_OFFSET)

#define RCC_CFG_REG_OFFSET		0x08
#define RCC_CFG_REG_ADDR		(RCC_BASE_ADDR + RCC_CFG_REG_OFFSET)

#define RCC_GPIOC_REG_OFFSET	0x30
#define RCC_GPIOC_REG_ADDR		(RCC_BASE_ADDR + RCC_GPIOC_REG_OFFSET)

#define GPIOC_BASE_ADDR			0x40020800UL
#define GPIOC_MODER_OFFSET		0x00
#define GPIOC_MODER_ADDR		(GPIOC_BASE_ADDR + GPIOC_MODER_OFFSET)

#define GPIOC_AFRH_OFFSET		0x24
#define GPIOC_AFRH_ADDR			(GPIOC_BASE_ADDR + GPIOC_AFRH_OFFSET)


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
		uint32_t *pRccCRReg = (uint32_t*) (RCC_CR_REG_ADDR);
		*pRccCRReg |= (1<<18);
		*pRccCRReg |= (1<<16);
		while(!(*pRccCRReg&(1<<17)));

		uint32_t *pRccCfgrReg = (uint32_t*) (RCC_CFG_REG_ADDR);
		*pRccCfgrReg |= (0x1<<0);
		//Configure MCO2 Clock output
		*pRccCfgrReg |= (0x1<<31);	//Clear 30th and 31st bit
		//Configure prescalar for Oscillator
		*pRccCfgrReg |= (0x4<<27);	//Clear 30th and 31st bit

		//Configure RCC CFGR register to select the HSI as clock-source
		//*pRccCfgrReg &= ~(0x7<<27);	//Clear 30th and 31st bit

		//Configure GPIOC to enable clock to its port
		uint32_t *pRccAhb1Enr = (uint32_t*)(RCC_GPIOC_REG_ADDR);
		*pRccAhb1Enr |= (1<<2);

		//Configure PORTC to AF0 to activate the MCO2 function
		uint32_t *pGPIOCModeReg =	(uint32_t*)(GPIOC_MODER_ADDR);
		*pGPIOCModeReg &= ~(0x3<<18);
		*pGPIOCModeReg |= (0x2<<18);

		//Configure PC9 to AF0 to activate the MCO2 function
		//Inorder to configure PC9 to AF0 we need to select the AFRH register since it holds the 9th pin control to PortC
		uint32_t *pGPIOC_AFHReg =	(uint32_t*)(GPIOC_AFRH_ADDR);
		*pGPIOC_AFHReg &= ~(0xF<<4);

    /* Loop forever */
	for(;;);
}
