/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE_ADDR			0x40023800UL
#define RCC_PLL_REG_OFFSET		0x04
#define RCC_PLL_REG_ADDR		(RCC_BASE_ADDR + RCC_PLL_REG_OFFSET)

#define RCC_CFG_REG_OFFSET		0x08
#define RCC_CFG_REG_ADDR		(RCC_BASE_ADDR + RCC_CFG_REG_OFFSET)

#define RCC_GPIOC_REG_OFFSET	0x30
#define RCC_GPIOC_REG_ADDR		(RCC_BASE_ADDR + RCC_GPIOC_REG_OFFSET)

#define GPIOC_BASE_ADDR			0x40020800UL
#define GPIOC_MODER_OFFSET		0x00
#define GPIOC_MODER_ADDR		(GPIOC_BASE_ADDR + GPIOC_MODER_OFFSET)

#define GPIOC_AFHR_OFFSET		0x24
#define GPIOC_AFHR_ADDR			(GPIOC_BASE_ADDR + GPIOC_AFHR_OFFSET)

//#define RCC_GPIOA_REG_OFFSET	0x30
//#define RCC_GPIOA_REG_ADDR		(RCC_BASE_ADDR + RCC_GPIOC_REG_OFFSET)
//
//#define GPIOA_BASE_ADDR			0x40020800UL
//#define GPIOA_MODER_OFFSET		0x00
//#define GPIOA_MODER_ADDR		(GPIOC_BASE_ADDR + GPIOC_MODER_OFFSET)
//
//#define GPIOA_AFHR_OFFSET		0x24
//#define GPIOA_AFHR_ADDR			(GPIOC_BASE_ADDR + GPIOC_AFHR_OFFSET)


//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

int main(void)
{
//	uint32_t *pRccPllReg = (uint32_t*) (RCC_PLL_REG_ADDR);
//	*pRccPllReg |= (1<<0);

	uint32_t *pRccCfgrReg = (uint32_t*) (RCC_CFG_REG_ADDR);
	*pRccCfgrReg &= ~(0x3<<21);	//Clear 30th and 31st bit

	//Configure prescalar for portC
	*pRccCfgrReg |= (0x6<<27);	//Clear 30th and 31st bit

	//Configure RCC CFGR register to select the HSI as clock-source
//	*pRccCfgrReg &= ~(0x7<<27);	//Clear 30th and 31st bit

	//Configure GPIOC to enable clock to its port
	uint32_t *pRccAhb1Enr = (uint32_t*)(RCC_GPIOC_REG_ADDR);
	*pRccAhb1Enr |= (1<<2);

	//Configure PC9 to AF0 to activate the MCO2 function
	uint32_t *pGPIOCModeReg =	(uint32_t*)(GPIOC_MODER_ADDR);
	*pGPIOCModeReg &= ~(0x3<<18);
	*pGPIOCModeReg |= (0x2<<18);

	//Configure PC9 to AF0 to activate the MCO2 function
	uint32_t *pGPIOC_AFHReg =	(uint32_t*)(GPIOC_AFHR_ADDR);
	*pGPIOC_AFHReg &= ~(0xF<<4);


    /* Loop forever */
		for(;;);
}
